name: Build Checkers Mini Chain
on: 
  push:
    branches:
      - main
jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install go-testreport
        run: |
          go install github.com/becheran/go-testreport@latest

      - name: Run tests with coverage
        run: |
          go test ./... -coverprofile=coverage.out -json > test-report.json

      - name: Generate test report
        run: |
          cat test-report.json | go-testreport $GITHUB_STEP_SUMMARY

  build:
    needs: [test-and-report]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [darwin, linux]
        include:
          - targetos: darwin
            arch: arm64
    name: mini ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile mini
        run: |
          go mod download
          cd cmd/minid
          go build .

      - uses: actions/upload-artifact@v4
        with:
          name: minid ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/minid/minid
